version: "2"
exclude_patterns:
- "**/scala-3.x"
- "**/native"
- "**/js"
- "**/test"
- ".github"
- "project"
- "build.sbt"
- "*.md"
- ".codeclimate.yml"
- ".gitignore"
- "*.pdf"
- "LICENSE"
- "**/lift.scala"
- "**/implicits/zipped.scala"
plugins:
  scalastyle:
    enabled: true
    checks:
      org.scalastyle.scalariform.NoWhitespaceBeforeLeftBracketChecker:
        enabled: false
      org.scalastyle.scalariform.NullChecker:
        enabled: false
      org.scalastyle.file.NewLineAtEofChecker:
        enabled: false
      org.scalastyle.scalariform.IfBraceChecker:
        enabled: false
      org.scalastyle.scalariform.MethodNamesChecker:
        enabled: false
      org.scalastyle.scalariform.ObjectNamesChecker:
        enabled: false
      org.scalastyle.scalariform.ClassNamesChecker:
        enabled: false
      org.scalastyle.scalariform.LowercasePatternMatchChecker:
        enabled: false
      org.scalastyle.scalariform.MultipleStringLiteralsChecker:
        enabled: false
      org.scalastyle.scalariform.ClassTypeParameterChecker:
        enabled: false