version: "2"
exclude_patterns:
- "**/scala-3"
- "**/scala-2.12"
- "**/native"
- "**/js"
- "**/js-native"
- "**/test"
- ".github"
- "project"
- "build.sbt"
- "*.md"
- ".codeclimate.yml"
- ".gitignore"
- "*.pdf"
- "LICENSE"
- "**/ap.scala"
- "**/lift.scala"
- "**/generic.scala"
- "**/syntax/zipped.scala"
- "**/syntax/lift.scala"
plugins:
  scalastyle:
    enabled: true
    config:
      config: scalastyle-config.xml
    checks:
      org.scalastyle.scalariform.ForBraceChecker:
        enabled: false
