/*
 * Copyright 2020 Parsley Contributors <https://github.com/j-mie6/Parsley/graphs/contributors>
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
package parsley.token

/** This package contains the relevant functionality for configuring the error messages generated by the parsers provided by the `Lexer` class.
  *
  * @groupprio errconfig 5
  * @groupname errconfig Error Configuration
  * @groupdesc errconfig This is the main class that defines the configuration for errors from the `Lexer`.
  *
  * @groupprio labels 5
  * @groupname labels Labelling and Explain Configuration
  * @groupdesc labels These classes can be used to configure both labels and/or explains for simple description configurations.
  *
  * @groupprio filters 10
  * @groupname filters Filtering Configuration
  * @groupdesc filters These classes can be used to describe how to generate the filters to rule out specific parses. They can used to either generate
  *                    types of ''vanilla'' error or ''specialised'' errors.
  *
  * @groupprio doubledot 20
  * @groupname doubledot Preventing Double Dot
  * @groupdesc doubledot These classes and objects help to configure the ''Preventative Error'' pattern for bad `.`s,
  *                      used by [[parsley.token.errors.ErrorConfig.preventRealDoubleDroppedZero `peventRealDoubleDroppedZero`]].
  *
  * @groupprio badchar 20
  * @groupname badchar Verifying Bad Characters
  * @groupdesc badchar These classes can be used to help configure the ''Verified Error'' pattern for illegal string and character literal characters,
  *                    used by [[parsley.token.errors.ErrorConfig.verifiedCharBadCharsUsedInLiteral `verifiedCharBadCharsUsedInLiteral`]] and
  *                    [[parsley.token.errors.ErrorConfig.verifiedStringBadCharsUsedInLiteral `verifiedStringBadCharsUsedInLiteral`]].
  */
package object errors
