name: CI
on: [push, pull_request, workflow_dispatch]
env:
  CI: true
  CI_SNAPSHOT_RELEASE: +publishSigned
  SCALA_VERSION: 2.13.4
jobs:
  check-duplicate:
    name: Check duplicate action
    runs-on: ubuntu-20.04
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content'
  validate:
    name: Scala ${{ matrix.scala }}, Java ${{ matrix.java }}
    runs-on: ubuntu-20.04
    needs: check-duplicate
    if: ${{ needs.check-duplicate.outputs.should_skip != 'true' }}
    strategy:
      fail-fast: false
      matrix:
        java: [adopt@1.8, adopt@1.11, adopt@1.15]
        scala: [2.12.13, 2.13.4, 3.0.0-M3]
        experimental: [false]
        include:
          - java: adopt@1.11
            scala: 0.27.0-RC1
            experimental: true
    env:
      SCALA_VERSION: ${{ matrix.scala }}
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: sbt-coursier-cache
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}
      - name: Test
        run: sbt ++$SCALA_VERSION test
      - name: Scaladoc
        run: sbt ++$SCALA_VERSION doc
  coverage:
    needs: validate
    name: Test Coverage
    if: |
      github.ref == 'refs/heads/master' && (needs.check-duplicate.result == 'success' || needs.check-duplicate.result == 'skipped') ||
      github.event_name == 'pull_request' && needs.check-duplicate.result == 'success'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: sbt-coursier-cache
      - uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}
      - run: sbt ++$SCALA_VERSION clean coverage test
      - run: sbt ++$SCALA_VERSION coverageReport
      - uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: d2376ef4077556821a44dd82803411deea8fd904d5008713754dda5f3ab42875
        with:
          coverageLocations: ${{github.workspace}}/target/scala-2.13/coverage-report/cobertura.xml:cobertura
