name: Release

on:
  push:
    branches:
      - master
    tags:
      - '*'
  workflow_dispatch:

env:
#  WARN: Updating sbt ci-release to any version past 1.5.4 changes the default (+publishSigned) to +publish
#  CI_SNAPSHOT_RELEASE: +publishSigned
#  Temp: testing if SCALA_VERSION is needed
#  SCALA_VERSION: 2.12.13

jobs:
  release:
    name: Release

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Setup Scala
        uses: olafurpg/setup-scala@v10

      - name: Setup GPG
        uses: olafurpg/setup-gpg@v3

      - name: Cache Coursier
        uses: actions/cache@v2
        with:
          path: ~/.cache/coursier
          key: sbt-coursier-cache

      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}

      - name: Publish
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
